### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tomwilkie** [terraform-providers/terraform-provider-vault#55]
```
$ ls .terraform/plugins/darwin_amd64/
lock.json                           terraform-provider-aws_v1.6.0_x4    terraform-provider-vault_v1.0.0_x4  
```

```
$ terraform version
Terraform v0.10.8
```

```
2018-01-11T18:18:41.485Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 2018/01/11 18:18:41 [DEBUG] secret: (*api.Secret)(nil)
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x167026e]
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: goroutine 82 [running]:
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.genericSecretResourceRead(0xc4202c3180, 0x1803de0, 0xc420121860, 0x1, 0x1d3e840)
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_generic_secret.go:153 +0x2ce
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420053920, 0xc420128f00, 0x1803de0, 0xc420121860, 0xc42007beb8, 0xc4203ec401, 0x80000000018)
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:321 +0x199
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42008ec40, 0xc420128eb0, 0xc420128f00, 0x1f1b6c8, 0x0, 0x18)
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:284 +0x9a
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4200e59e0, 0xc420125ef0, 0xc420125ff0, 0x0, 0x0)
2018-01-11T18:18:41.487Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: reflect.Value.call(0xc420052840, 0xc42012c0f8, 0x13, 0x18310b8, 0x4, 0xc4203acf20, 0x3, 0x3, 0x0, 0x0, ...)
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x906
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: reflect.Value.Call(0xc420052840, 0xc42012c0f8, 0x13, 0xc420027720, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: net/rpc.(*service).call(0xc420126b00, 0xc420128230, 0xc420146210, 0xc420148700, 0xc42012a540, 0x16cfb60, 0xc420125ef0, 0x16, 0x16cfba0, 0xc420125ff0, ...)
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: created by net/rpc.(*Server).ServeCodec
2018-01-11T18:18:41.488Z [DEBUG] plugin.terraform-provider-vault_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by paultyng** [comment]
If read secret is nil, need to set id to empty before this: https://github.com/terraform-providers/terraform-provider-vault/blob/7c950195ae62bd2aad612e15b8dc71e52084580b/vault/resource_generic_secret.go#L153

**Comment by jgiles** [comment]
@paultyng can we get a new release of the provider with this fix included?
