### ISSUE TITLE
unexpected EOF when applying vault_aws_auth_backend_role

### ISSUE THREAD

**Issue by yongzhang** [terraform-providers/terraform-provider-vault#691]
vault version: 1.3.2
vault tf provider version: 1.9.0
tf version: 0.11.11

code:
```
resource "vault_aws_auth_backend_role" "sre_vault" {
  backend                  = "aws"
  role                     = "sre-vault"
  auth_type                = "iam"
  bound_iam_principal_arns = ["arn:aws-cn:iam::xxx:role/vault"]
  ttl                      = 3600
  max_ttl                  = 7776000
  policies                 = ["default", "sre-vault"]
}

```

error (creating):
```
* vault_aws_auth_backend_role.sre_vault: 1 error(s) occurred:
* vault_aws_auth_backend_role.sre_vault: unexpected EOF
```

Trace log:
```
2020-02-26T14:57:19.540+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: -----------------------------------------------------
2020-02-26T14:57:19.540+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: 2020/02/26 14:57:19 [DEBUG] Read AWS auth backend role "auth/aws/role/sre-vault"
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: panic: interface conversion: interface {} is nil, not json.Number
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: goroutine 489 [running]:
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.awsAuthBackendRoleRead(0xc00021e230, 0x1152880, 0xc000ae1490, 0x1, 0x1)
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_aws_auth_backend_role.go:452 +0x1b20
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.awsAuthBackendRoleCreate(0xc00021e230, 0x1152880, 0xc000ae1490, 0xc00021e230, 0x0)
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_aws_auth_backend_role.go:408 +0xc7b
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc00072ac40, 0xc0002ac6e0, 0xc0005bf4e0, 0x1152880, 0xc000ae1490, 0x40b801, 0xc000584b80, 0x4c1fec)
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:225 +0x351
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000ae0b60, 0xc0002ac690, 0xc0002ac6e0, 0xc0005bf4e0, 0xc00008ea80, 0x18, 0x7f117d8f2880)
2020-02-26T14:57:19.543+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0x9c
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc000150e60, 0xc0005bf480, 0xc000b00f40, 0x0, 0x0)
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: reflect.Value.call(0xc00058c5a0, 0xc000881de0, 0x13, 0x116be2f, 0x4, 0xc000584f18, 0x3, 0x3, 0xc0004833c0, 0xc000676300, ...)
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/goenv/versions/1.11.0/src/reflect/value.go:447 +0x449
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: reflect.Value.Call(0xc00058c5a0, 0xc000881de0, 0x13, 0xc000061f18, 0x3, 0x3, 0x0, 0xc0005e28a0, 0x0)
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/goenv/versions/1.11.0/src/reflect/value.go:308 +0xa4
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: net/rpc.(*service).call(0xc00099fb40, 0xc0002ac4b0, 0xc0006af520, 0xc0006af530, 0xc000884680, 0xc0005bf460, 0xf3cb60, 0xc0005bf480, 0x16, 0xf3cba0, ...)
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/goenv/versions/1.11.0/src/net/rpc/server.go:384 +0x14e
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4: created by net/rpc.(*Server).ServeCodec
2020-02-26T14:57:19.544+0800 [DEBUG] plugin.terraform-provider-vault_v1.9.0_x4:         /opt/goenv/versions/1.11.0/src/net/rpc/server.go:481 +0x47e
2020/02/26 14:57:19 [TRACE] root: eval: *terraform.EvalWriteState
2020/02/26 14:57:19 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2020/02/26 14:57:19 [TRACE] root: eval: *terraform.EvalIf
2020/02/26 14:57:19 [TRACE] root: eval: *terraform.EvalWriteState
2020/02/26 14:57:19 [TRACE] root: eval: *terraform.EvalWriteDiff
2020/02/26 14:57:19 [TRACE] root: eval: *terraform.EvalApplyPost
2020/02/26 14:57:19 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vault_aws_auth_backend_role.sre_vault: unexpected EOF
2020/02/26 14:57:19 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vault_aws_auth_backend_role.sre_vault: unexpected EOF
2020/02/26 14:57:19 [TRACE] [walkApply] Exiting eval tree: vault_aws_auth_backend_role.sre_vault
```

**Comment by vngzs** [comment]
Looks like another instance of this here: https://gist.github.com/infa-bsurber/0836c5f87a5b3091261e479a07903394

I get it myself additionally.

**Comment by yongzhang** [comment]
@vngzs I upgraded vault provider version to 2.8.0 fixed this issue.
